# Generated by Django 4.2.4 on 2024-04-03 10:58

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=12, prefix='our_works', unique=True)),
                ('category_title', models.CharField(default='Walpapers', max_length=100)),
                ('status', models.CharField(choices=[('disabled', 'Disabled'), ('published', 'Published')], default='published', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Our Work',
            },
        ),
        migrations.CreateModel(
            name='WorksImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('images', models.ImageField(default='work_images.jpg', upload_to='product-images')),
                ('videos', models.FileField(blank=True, default='work_videos.mp4', null=True, upload_to='product-videos')),
                ('works', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.works')),
            ],
            options={
                'verbose_name_plural': 'Our Work Images',
            },
        ),
    ]
