# Generated by Django 4.2.4 on 2024-04-10 16:47

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_alter_worksimages_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefgh12345",
                        length=22,
                        max_length=12,
                        prefix="our_works",
                        unique=True,
                    ),
                ),
                (
                    "media_address",
                    models.CharField(default="Ring Road...", max_length=100),
                ),
                (
                    "images",
                    models.ImageField(
                        default="media_images.jpg", upload_to="product-images"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("disabled", "Disabled"), ("published", "Published")],
                        default="published",
                        max_length=10,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Our Media",},
        ),
    ]
