# Generated by Django 4.2.4 on 2024-04-10 18:26

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="architectureimages",
            name="location",
            field=models.CharField(default="south ex..", max_length=100),
        ),
        migrations.AlterField(
            model_name="media",
            name="mid",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=22,
                max_length=31,
                prefix="our_works",
                unique=True,
            ),
        ),
    ]
