# Generated by Django 4.2.4 on 2024-04-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_architectureimages_location_alter_media_mid"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksimages",
            name="brand_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="worksimages",
            name="link_to_brand",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
