# Generated by Django 4.2.4 on 2024-04-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_worksimages_brand_name_worksimages_link_to_brand"),
    ]

    operations = [
        migrations.RemoveField(model_name="blogs", name="blog_tags",),
        migrations.RemoveField(model_name="blogs", name="canonical_link",),
        migrations.RemoveField(model_name="blogs", name="meta_robots",),
        migrations.RemoveField(model_name="blogs", name="meta_tag",),
        migrations.RemoveField(model_name="blogs", name="meta_title",),
        migrations.RemoveField(model_name="blogs", name="og_description",),
        migrations.RemoveField(model_name="blogs", name="og_image",),
        migrations.RemoveField(model_name="blogs", name="og_title",),
        migrations.RemoveField(model_name="blogs", name="og_url",),
        migrations.RemoveField(model_name="blogs", name="twitter_description",),
        migrations.RemoveField(model_name="blogs", name="twitter_title",),
        migrations.AddField(
            model_name="blogs",
            name="focus_keyword",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogs",
            name="permalink",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogs",
            name="meta_description",
            field=models.CharField(max_length=500),
        ),
    ]
